version: '3'

services:
  auth-svc:
    image: 'auth-svc:dev'
    container_name: 'auth-svc'
    build:
      context: './microservices/auth-svc'
    ports:
      - '50051:50051'
    # expose:
    # - "50051"
    environment:
      NODE_ENV: 'production'
      GRPC_HOST: '0.0.0.0'
      GRPC_PORT: '50051'
      DB_HOST: 'micro-auth'
    # healthcheck:
    #   test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    restart: 'on-failure'

  # product-svc:
  #   image: "product-svc:dev"
  #   container_name: "product-svc"
  #   build:
  #     context: "./microservices/product-svc"
  #   networks:
  #     - "frontend"
  #     - "backend"
  #     - "productdomain"
  #   expose:
  #     - "50053"
  #   environment:
  #     NODE_ENV: "production"
  #     GRPC_HOST: "0.0.0.0"
  #     GRPC_PORT: "50053"
  #     DB_HOST: "micro-product"
  #   # healthcheck:
  #   #   test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
  #   #   interval: 30s
  #   #   timeout: 10s
  #   #   retries: 5
  #   restart: "on-failure"

  # order-svc:
  #   image: "order-svc:dev"
  #   container_name: "order-svc"
  #   build:
  #     context: "./microservices/order-svc"
  #   networks:
  #     - "frontend"
  #     - "backend"
  #     - "orderdomain"
  #   expose:
  #     - "50052"
  #   environment:
  #     NODE_ENV: "production"
  #     GRPC_HOST: "0.0.0.0"
  #     GRPC_PORT: "50052"
  #     DB_HOST: "micro-order"
  #   # healthcheck:
  #   #   test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
  #   #   interval: 30s
  #   #   timeout: 10s
  #   #   retries: 5
  #   restart: "on-failure"

  api-gateway:
    image: 'api-gateway:dev'
    container_name: 'api-gateway'
    build:
      context: './api-gateway'
    ports:
      - '3000:3000'
    depends_on:
      - 'auth-svc'
      # - "order-svc"
      # - "product-svc"
    environment:
      NODE_ENV: 'test'
      PORT: '3000'
      GRAPHQL_PORT: '3000'
      JWT_ACCESSTOKEN_SECRET: 'VtWeuJo5cPrH1gzvLX0HwPkcbVVeMkV0/a2JFeP3hGE='
      JWT_REFRESHTOKEN_SECRET: 'tPQz6vb7nJDilma85OQExilvgZX+QyEf1CL95DmfBLA='
      JWT_ISSUER: 'application'
      JWT_AUDIENCE: 'public'
      AUTH_SVC_URL: 'auth-svc:50051'
      PRODUCT_SVC_URL: 'order-svc:50052'
      ORDER_SVC_URL: 'product-svc:50053'
    # healthcheck:
    #   test: ["CMD", "wget", "localhost:3000/healthz -q -O - > /dev/null 2>&1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    restart: 'on-failure'
# networks:
#   frontend:
#   backend:
#   authdomain:
#   productdomain:
#   orderdomain:
