version: '3'

services:
  auth-svc:
    image: 'auth-svc:prod'
    container_name: 'auth-svc'
    build:
      context: './microservices/auth-svc'
      target: production
    networks:
      - backend
    expose:
      - 50051
    # ports:
    environment:
      NODE_ENV: 'production'
      GRPC_URL: '0.0.0.0:50051'
      DB_TYPE: 'mongodb+srv://'
      DB_NAME: 'micro-auth'
      DB_USERNAME: 'admin'
      DB_PASSWORD: 'denialcode'
      DB_CLUSTER: "@cluster0.k21st.gcp.mongodb.net"
    # healthcheck:
    #   test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    restart: 'on-failure'

  order-svc:
    image: 'order-svc:prod'
    container_name: 'order-svc'
    build:
      context: './microservices/order-svc'
      target: production
    networks:
      - backend
    expose:
      - 50052
    environment:
      NODE_ENV: 'production'
      GRPC_URL: '0.0.0.0:50052'
      DB_TYPE: 'mongodb+srv://'
      DB_NAME: 'micro-order'
      DB_USERNAME: 'admin'
      DB_PASSWORD: 'denialcode'
      DB_CLUSTER: "@cluster0.k21st.gcp.mongodb.net"
      PRODUCT_SVC_URL: 'product-svc:50053'
      
    # healthcheck:
    #   test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    restart: 'on-failure'

  product-svc:
    image: 'product-svc:prod'
    container_name: 'product-svc'
    build:
      context: './microservices/product-svc'
      target: production
    networks:
      - backend
    expose:
      - 50053
    environment:
      NODE_ENV: 'production'
      GRPC_URL: '0.0.0.0:50053'
      DB_TYPE: 'mongodb+srv://'
      DB_NAME: 'micro-product'
      DB_USERNAME: 'admin'
      DB_PASSWORD: 'denialcode'
      DB_CLUSTER: "@cluster0.k21st.gcp.mongodb.net"
      
    # healthcheck:
    #   test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    restart: 'on-failure'

  api-gateway:
    image: 'api-gateway:prod'
    container_name: 'api-gateway'
    build:
      context: './api-gateway'
      target: production
    networks:
      - api-gateway
      - backend
    ports:
      - 3000:3000
    depends_on:
      - 'auth-svc'
      - 'product-svc'
      - 'order-svc'
    environment:
      NODE_ENV: 'production'
      PORT: '3000'
      GRAPHQL_PORT: '3000'
      JWT_ACCESSTOKEN_SECRET: 'VtWeuJo5cPrH1gzvLX0HwPkcbVVeMkV0/a2JFeP3hGE='
      JWT_REFRESHTOKEN_SECRET: 'tPQz6vb7nJDilma85OQExilvgZX+QyEf1CL95DmfBLA='
      JWT_ISSUER: 'application'
      JWT_AUDIENCE: 'public'
      AUTH_SVC_URL: 'auth-svc:50051'
      ORDER_SVC_URL: 'order-svc:50052'
      PRODUCT_SVC_URL: 'product-svc:50053'
    # healthcheck:
    #   test: ["CMD", "wget", "localhost:3000/healthz -q -O - > /dev/null 2>&1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    restart: 'on-failure'

networks:
  api-gateway: {}
  backend: {}
